---
name: workflow for running azure terraform code
on:
  pull_request:
    branches: [master]
  push:
    branches: [devolopmnent]

env:
  #TERRAFORM_DESTROY: "YES"
  ENVIRONMENT: "Development"
  ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
  ACTIONS_STEP_DEBUG: true

jobs:
  tools_check:
    name: "Checking Tools Status"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Print Runner Hostname
        run: hostname
        shell: bash
      - name: Print Runner IP Address
        run: curl -sL https://ipconfig.io
        shell: bash
